# HelloFresh Recipe AI - Food Detection Dataset Configuration
# YOLO data configuration for food ingredient detection

# Dataset paths
path: ./data  # Root directory
train: train/images  # Training images (relative to 'path')
val: val/images      # Validation images (relative to 'path') 
test: test/images    # Test images (relative to 'path')

# Number of classes
nc: 20

# Class names for food ingredients
names:
  0: apple
  1: banana
  2: orange
  3: carrot
  4: broccoli
  5: tomato
  6: potato
  7: onion
  8: bell_pepper
  9: cucumber
  10: bread
  11: egg
  12: milk
  13: cheese
  14: chicken
  15: beef
  16: fish
  17: pasta
  18: rice
  19: salad