# HelloFresh Recipe AI - Text Detection Dataset Configuration
# YOLO data configuration for ingredient text block detection

# Dataset paths
path: ./data  # Root directory
train: train/images  # Training images (relative to 'path')
val: val/images      # Validation images (relative to 'path') 
test: test/images    # Test images (relative to 'path')

# Number of classes
nc: 2

# Class names optimized for ingredient text blocks
names:
  0: ingredient_line  # Complete ingredient lines (e.g., "2 cups flour")
  1: ingredient_block # Multi-line ingredient blocks